In [12]:
import torch
import torch.nn
import torch.nn.functional as F

a = torch.arange(32)

b = a.reshape((4,8))

print(b.permute(1,0))

b % 2

A = torch.ones((4,4))
B = torch.zeros((4,4))
errAB = F.mse_loss(A,B)
print(errAB)

A[1,:].size()
import gradientGenerator
a = torch.rand(4, 5, 14,32)
att = gradientGenerator.PixelwiseSelfAttention2d(5,1)
print(att(a)[0].size())

print(gradientGenerator.modelNParam(
    gradientGenerator.PixelwiseSelfAttention2d(128, 4)))

mres = gradientGenerator.ResNetForwardA(4,2,3)

din = torch.rand(16,4,100,100)

print(mres(din).size())

print(torch.meshgrid([torch.tensor([0,1]),torch.tensor([0,1,2])], indexing = 'ij'))
print(gradientGenerator.PosEncoding2D((2,8,3,5), 64, 'cpu'))


tensor([[ 0,  8, 16, 24],
        [ 1,  9, 17, 25],
        [ 2, 10, 18, 26],
        [ 3, 11, 19, 27],
        [ 4, 12, 20, 28],
        [ 5, 13, 21, 29],
        [ 6, 14, 22, 30],
        [ 7, 15, 23, 31]])
tensor(1.)
torch.Size([5, 14, 32])
66304
torch.Size([16, 4, 100, 100])
(tensor([[0, 0, 0],
        [1, 1, 1]]), tensor([[0, 1, 2],
        [0, 1, 2]]))
tensor([[[[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
          [ 0.5403,  0.5403,  0.5403,  0.5403,  0.5403],
          [-0.4161, -0.4161, -0.4161, -0.4161, -0.4161]],

         [[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
          [ 0.9922,  0.9922,  0.9922,  0.9922,  0.9922],
          [ 0.9689,  0.9689,  0.9689,  0.9689,  0.9689]],

         [[ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536],
          [ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536],
          [ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536]],

         [[ 1.0000,  0.9922,  0.9689,  0.9305,  0.8776],
          [ 1.0000,  0.9922,  0.9689,  0.9305,  0.8776],
      